services:
  - type: web
    name: aurora-backend
    env: python
    rootDir: Backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn aurora.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aurora.settings
      - key: PORT
        value: 8000


