services:
  - type: web
    name: aurora-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aurora.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/Backend
      - key: PORT
        value: 8000 