services:
  - type: web
    name: aurora-backend
    env: python
    rootDir: Backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd Backend && gunicorn aurora.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: TURSO_DB_URL
        value: "libsql://your-db-name-username.turso.io"
      - key: TURSO_AUTH_TOKEN
        value: "your-token-here"  # Get via `turso db tokens create your-db-name`
      - key: DJANGO_SETTINGS_MODULE
        value: "aurora.settings"


