services:
  - type: web
    name: aurora-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aurora.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aurora.settings
      - key: PORT
        value: 8000
