services:
  - type: web
    name: aurora-backend
    env: python
    rootDir: Backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src/Backend
      gunicorn aurora.wsgi:application --bind 0.0.0.0:$PORT --chdir /opt/render/project/src/Backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aurora.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/Backend
      - key: PORT
        value: 8000

