services:
  - type: web
    name: aurora
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn aurora.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.mtvhwwjxisesiydcruab:kano12345@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: aurora-db
    databaseName: aurora
    user: aurora
    plan: free



