services:
  - type: web
    name: aurora
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn aurora.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aurora-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"

   
    
     
