services:
  - type: web
    name: aurora-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aurora.wsgi:application
    envVars:
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_HOST
        value: db.mtvhwwjxisesiydcruab.supabase.co
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
