# Generated by Django 5.1.7 on 2025-05-14 20:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='product',
            name='social_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
